// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb_vliw.cpp — Verilator C++ testbench for the BPS-V VLIW dispatcher.
//
// Loads a bundle image (produced by util/bundle_asm.py) into the bundle cache
// via the fill port, drives fetch_enable, models the external data bus for
// MMIO/external memory, detects halt (no activity), and checks the expected
// GPR values against the .expect file.
//
// The dispatcher does not (yet) expose its internal register file directly,
// so GPR checking is done by reading the VLIW RF array via Verilator's
// DPI/public-requirement mechanism. To enable that, the RF array in
// ibex_register_file_vliw.sv is marked /* verilator public */ (see Makefile
// VLV_ARG). This TB reaches in via dut->vliw_i->u_rf->rf[index].
//
// Usage:  tb_vliw <image> <expect> <width> [<max_cycles>]
//   width must match the assembler's width.

#include <verilated.h>
#if VM_TRACE
#include <verilated_vcd_c.h>
#endif
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <unordered_map>
#include <vector>
#include <string>
#include <fstream>
#include <sstream>

// Generated by Verilator from ibex_vliw_dispatch.sv (top).
#include "Vibex_vliw_dispatch.h"
#include "Vibex_vliw_dispatch_ibex_vliw_dispatch.h"  // root dispatcher sub-class
#include "Vibex_vliw_dispatch_ibex_register_file_vliw__W4.h"  // RF (public)

// ---------------------------------------------------------------------------
// Tiny external memory model: word-addressed map.  Used for the external bus
// (addresses outside the banked on-chip window).
// ---------------------------------------------------------------------------
static std::unordered_map<uint32_t, uint32_t> ext_mem;
static bool ext_pending = false;   // a load response is due
static uint32_t ext_pending_addr = 0;

// ---------------------------------------------------------------------------
// Load a flat image of 32-bit little-endian instructions.
// ---------------------------------------------------------------------------
static std::vector<uint32_t> load_image(const char *path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) { fprintf(stderr, "cannot open %s\n", path); exit(1); }
    std::vector<uint8_t> bytes((std::istreambuf_iterator<char>(f)),
                                std::istreambuf_iterator<char>());
    std::vector<uint32_t> words;
    for (size_t i = 0; i + 4 <= bytes.size(); i += 4) {
        uint32_t w = 0;
        for (int b = 0; b < 4; b++) w |= (uint32_t)bytes[i+b] << (b*8);
        words.push_back(w);
    }
    return words;
}

// ---------------------------------------------------------------------------
// Expectations: list of (is_mem, index, expected_value).
// ---------------------------------------------------------------------------
struct Expect { bool is_mem; uint32_t idx; uint32_t val; };
static std::vector<Expect> load_expect(const char *path) {
    std::ifstream f(path);
    std::vector<Expect> exps;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty()) continue;
        Expect e;
        if (line[0] == 'x') {
            // xN=0xVAL
            size_t eq = line.find('=');
            e.is_mem = false;
            e.idx = (uint32_t)std::stoul(line.substr(1, eq-1));
            e.val = (uint32_t)std::stoul(line.substr(eq+1), nullptr, 16);
        } else {
            // mem[0xADDR]=0xVAL
            size_t lb = line.find('[');
            size_t rb = line.find(']');
            size_t eq = line.find('=');
            e.is_mem = true;
            e.idx = (uint32_t)std::stoul(line.substr(lb+1, rb-lb-1), nullptr, 16);
            e.val = (uint32_t)std::stoul(line.substr(eq+1), nullptr, 16);
        }
        exps.push_back(e);
    }
    return exps;
}

// ---------------------------------------------------------------------------
// Main testbench loop.
// ---------------------------------------------------------------------------
int main(int argc, char **argv) {
    if (argc < 4) {
        fprintf(stderr, "usage: %s <image> <expect> <width> [<max_cycles>]\n", argv[0]);
        return 2;
    }
    const char *img_path = argv[1];
    const char *exp_path = argv[2];
    int width = std::atoi(argv[3]);
    long max_cycles = (argc > 4) ? std::atol(argv[4]) : 10000;

    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);
    Vibex_vliw_dispatch *dut = new Vibex_vliw_dispatch;
    VerilatedVcdC *tfp = nullptr;
#if VM_TRACE
    tfp = new VerilatedVcdC;
    dut->trace(tfp, 99);
    tfp->open("vliw_trace.vcd");
#endif

    std::vector<uint32_t> words = load_image(img_path);
    std::vector<Expect> exps = load_expect(exp_path);

    // ---- Fill-state machine: load slots into the bundle cache one per cycle.
    int fill_idx = 0;
    bool fill_done = false;
    int log2_width = 0; while ((1 << log2_width) < width) log2_width++;
    int slots_per_bundle = width;
    int bank_bits = (width > 1) ? log2_width : 0;

    // ---- Clock / reset ----
    auto tick = [&](int clk) {
        dut->clk_i = clk;
        dut->clk_sram_2x_i = clk; // tie 2x to core for sim (no real PLL)
        dut->eval();
    };

    dut->rst_ni = 0;
    dut->fetch_enable_i = 0;
    dut->fill_req_i = 0;
    dut->data_gnt_i = 0;
    dut->data_rvalid_i = 0;
    dut->data_rdata_i = 0;
    dut->data_err_i = 0;
    tick(0); tick(1); tick(0);
    dut->rst_ni = 1;

    long cyc = 0;
    bool halted = false;
    int idle_cycles = 0;

    while (cyc < max_cycles && !halted) {
        // ---- Phase 1: bundle-cache fill (one slot per cycle via fill port).
        if (!fill_done && fill_idx < (int)words.size()) {
            int bank = fill_idx % width;
            int addr = fill_idx / width;
            dut->fill_req_i    = 1;
            dut->fill_bank_i   = bank;
            dut->fill_addr_i   = addr;
            dut->fill_wdata_i  = words[fill_idx];
        } else {
            dut->fill_req_i = 0;
            if (!fill_done) fill_done = true;
        }

        // ---- Phase 2: once filled, assert fetch_enable.
        if (fill_done) dut->fetch_enable_i = 1;

        // ---- Phase 3: external bus model.
        // Respond to external requests with 1-cycle latency.
        if (ext_pending) {
            dut->data_rvalid_i = 1;
            dut->data_rdata_i = ext_mem[ext_pending_addr];
            ext_pending = false;
        } else {
            dut->data_rvalid_i = 0;
        }
        if (dut->data_req_o && !ext_pending) {
            dut->data_gnt_i = 1;
            if (dut->data_we_o) {
                ext_mem[dut->data_addr_o & ~3u] = dut->data_wdata_o;
            } else {
                ext_pending = true;
                ext_pending_addr = dut->data_addr_o & ~3u;
            }
        } else {
            dut->data_gnt_i = 0;
        }

        // ---- Clock edge ----
        tick(0);
#if VM_TRACE
        if (tfp) tfp->dump((vluint64_t)(cyc * 2));
#endif
        tick(1);
#if VM_TRACE
        if (tfp) tfp->dump((vluint64_t)(cyc * 2 + 1));
#endif
        cyc++;

        // ---- Advance fill index after the write. ----
        if (dut->fill_req_i && fill_idx < (int)words.size()) {
            fill_idx++;
        }

        // ---- Halt detection: the dispatcher asserts halted_o when any lane
        // decodes ebreak. Also halt on illegal (so we can inspect state on a
        // decode bug rather than spinning to timeout).
        if (fill_done) {
            if (dut->halted_o || dut->illegal_insn_o) {
                halted = true;
            }
        }
    }

    if (!halted) {
        fprintf(stderr, "TIMEOUT after %ld cycles (did not halt)\n", max_cycles);
        delete dut;
        return 1;
    }

    // ---- Check GPR values via the public RF array.
    // Verilator exposes the root dispatcher instance as dut->ibex_vliw_dispatch,
    // and the VLIW RF (marked /* verilator public */) at u_rf->rf[idx].
    int fails = 0;
    for (auto &e : exps) {
        if (e.is_mem) {
            uint32_t got = ext_mem[e.idx];
            if (got != e.val) {
                fprintf(stderr, "FAIL mem[0x%08x]: expected 0x%08x got 0x%08x\n",
                        e.idx, e.val, got);
                fails++;
            }
        } else {
            uint32_t got = dut->ibex_vliw_dispatch->u_rf->rf[e.idx];
            if (got != e.val) {
                fprintf(stderr, "FAIL x%u: expected 0x%08x got 0x%08x\n",
                        e.idx, e.val, got);
                fails++;
            }
        }
    }

    if (fails == 0) {
        printf("PASS  (%ld cycles)\n", cyc);
#if VM_TRACE
        if (tfp) tfp->close();
#endif
        delete dut;
        return 0;
    } else {
        printf("FAIL  (%d check failures, %ld cycles)\n", fails, cyc);
#if VM_TRACE
        if (tfp) tfp->close();
#endif
        delete dut;
        return 1;
    }
}
